sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev
  - sudo apt-get install -y libgtk2.0-dev

script:
  - make
